fix: fail when label is missing

diff --git a/.github/workflows/pr-label.yml b/.github/workflows/pr-label.yml
--- a/.github/workflows/pr-label.yml
+++ b/.github/workflows/pr-label.yml
@@ -34,12 +34,11 @@ jobs:
           echo "PR has one of the required labels."
           echo "label_valid=true" >> "$GITHUB_OUTPUT"
         else
-          echo "This PR is missing one of the required labels: bug, enhancement, or refactor."
+          echo "This PR is missing one of the required labels."
           echo "label_valid=false" >> "$GITHUB_OUTPUT"
         fi        
 
     - name: Update PR description to check "Added label" box
-      if: steps.check_label.outputs.label_valid == 'true'
       uses: actions/github-script@v7
       with:
         script: |
@@ -54,7 +53,7 @@ jobs:
             pull_number: prNumber,
           });
 
-          const labelValid = "${{ steps.check_label.outputs.label_valid }}";
+          const labelValid = ${{ steps.check_label.outputs.label_valid }};
 
           // Update the PR body based on whether required labels are present
           const updatedBody = labelValid === 'true'
@@ -69,3 +68,10 @@ jobs:
             pull_number: prNumber,
             body: updatedBody,
           });
+
+    - name: Fail if PR does not have the required labels
+      if: steps.check_label.outputs.label_valid == 'false'
+      run: |
+        echo "This PR is missing one of the required labels: bug, enhancement, or refactor."
+        exit 1
+        
